# Site settings
title: Francesco Pretelli
tag_text: Francesco Pretelli
description: Francesco Pretelli - Mobile Developer (and awesome guy)

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
