# site settings
title: Timelabs Ltd
subtitle: 
email: support@timelabs.io
description: we provide taylored mobile solutions for every need.
#  <br /> our time is your time
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.timelabs.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
